.local/bin/wsl-ssh-agent-relay:
  type: file
  url: 'https://raw.githubusercontent.com/rupor-github/wsl-ssh-agent/master/docs/wsl-ssh-agent-relay'
  executable: true

# This entry is just for npiperelay. Do it this way to make it much simpler.
.wsl:
  type: archive
  url: 'https://github.com/jstarks/npiperelay/releases/download/v0.1.0/npiperelay_windows_amd64.zip'
  include:
    - npiperelay.exe
